import BuildRightLogo from "../../../../../../assets/buildright-logo.png";
import CallComLogo from "../../../../../../assets/callcom_thumb.png";
import LogisticsSALogo from "../../../../../../assets/logistics_thumb.png";
import ConstructionLogo from "../../../../../../assets/constructionco_thumb.png";
import WarehouseProLogo from "../../../../../../assets/warehouse-logo.png";


export const mockJobs = [
  {
    id: 1,
    title: "Construction Supervisor",
    company: "BuildRight Construction",
    logo: BuildRightLogo,
    location: "Soweto, Johannesburg",
    salary: "R25,000 - R35,000",
    type: "Full-time",
    matches: "95% match",
    urgent: true,
    posted: "2 hours ago",
    skills: ["Leadership", "Construction", "Safety", "Team Management"],
    industry: "Construction",
    description: "Leading construction projects in Soweto, managing teams, ensuring safety compliance.",
    requirements: "5+ years construction experience, leadership skills, safety certification",
    category: "job",
    benefits: ["Medical Aid", "Provident Fund", "Training", "Growth Opportunities"]
  },
  {
    id: 2,
    title: "Warehouse Manager",
    company: "Unitrans Logistics",
    logo: LogisticsSALogo,
    location: "Johannesburg",
    salary: "R22,000 - R32,000",
    type: "Full-time",
    matches: "88% match",
    urgent: false,
    posted: "1 day ago",
    skills: ["Management", "Logistics", "Inventory", "Operations"],
    industry: "Logistics",
    description: "Oversee warehouse operations, manage inventory, lead warehouse staff in Gauteng.",
    requirements: "Warehouse experience, management skills, inventory knowledge",
    category: "job",
    benefits: ["Performance Bonus", "Transport Allowance", "Medical Insurance"]
  },
  {
    id: 3,
    title: "Construction Learnership",
    company: "WBHO Construction",
    logo: ConstructionLogo,
    location: "Pretoria",
    salary: "R8,000 - R12,000",
    type: "Learnership",
    matches: "92% match",
    urgent: true,
    posted: "1 day ago",
    skills: ["Willing to Learn", "Teamwork", "Basic Construction"],
    industry: "Construction",
    description: "12-month learnership program with on-the-job training and classroom learning.",
    requirements: "Matric certificate, no experience required",
    category: "learnership",
    benefits: ["NQF Certification", "Stipend", "Mentorship", "Job Placement"]
  },
  {
    id: 4,
    title: "Logistics Learnership",
    company: "Imperial Logistics",
    logo: WarehouseProLogo,
    location: "Durban",
    salary: "R9,000 - R13,000",
    type: "Learnership",
    matches: "85% match",
    urgent: false,
    posted: "3 days ago",
    skills: ["Organization", "Basic Computer", "Communication"],
    industry: "Logistics",
    description: "18-month learnership in warehouse operations and logistics management.",
    requirements: "Grade 12, good communication skills",
    category: "learnership",
    benefits: ["Certificate", "Monthly Stipend", "Career Guidance"]
  },
  {
    id: 5,
    title: "Community Volunteer",
    company: "Soweto Hope Centre",
    logo: BuildRightLogo,
    location: "Soweto",
    salary: "Volunteer",
    type: "Volunteer",
    matches: "98% match",
    urgent: true,
    posted: "5 hours ago",
    skills: ["Empathy", "Communication", "Community Service"],
    industry: "Community",
    description: "Support community outreach programs and assist with daily operations in Soweto.",
    requirements: "Passion for community work, good interpersonal skills",
    category: "volunteer",
    benefits: ["Certificate", "Experience", "Networking", "Meals Provided"]
  },
  {
    id: 6,
    title: "Environmental Volunteer",
    company: "Greenpeace South Africa",
    logo: LogisticsSALogo,
    location: "Cape Town",
    salary: "Volunteer",
    type: "Volunteer",
    matches: "90% match",
    urgent: false,
    posted: "2 days ago",
    skills: ["Environmental Awareness", "Teamwork", "Physical Fitness"],
    industry: "Environment",
    description: "Participate in environmental conservation projects and community education.",
    requirements: "Interest in environmental issues, team player",
    category: "volunteer",
    benefits: ["Training", "Certificate", "Community Recognition"]
  },
  {
    id: 7,
    title: "Business Intern",
    company: "Vodacom South Africa",
    logo: CallComLogo,
    location: "Johannesburg",
    salary: "R10,000 - R15,000",
    type: "Internship",
    matches: "87% match",
    urgent: true,
    posted: "1 day ago",
    skills: ["Communication", "Office Skills", "Customer Service"],
    industry: "Business",
    description: "6-month internship in business operations and customer service.",
    requirements: "Recent graduate, good communication skills",
    category: "internship",
    benefits: ["Stipend", "Mentorship", "Potential Employment"]
  },
  {
    id: 8,
    title: "IT Support Intern",
    company: "Dimension Data",
    logo: ConstructionLogo,
    location: "Sandton",
    salary: "R12,000 - R18,000",
    type: "Internship",
    matches: "82% match",
    urgent: false,
    posted: "4 days ago",
    skills: ["Basic IT", "Problem Solving", "Communication"],
    industry: "Technology",
    description: "12-month internship providing IT support and learning technical skills.",
    requirements: "Basic computer knowledge, willingness to learn",
    category: "internship",
    benefits: ["Training", "Certificate", "Tech Equipment", "Mentorship"]
  }
];

export const jobCategories = [
  { id: "All", label: "All Opportunities", icon: "Briefcase" },
  { id: "job", label: "Available Jobs", icon: "BriefcaseBusiness" },
  { id: "learnership", label: "Learnerships", icon: "GraduationCap" },
  { id: "volunteer", label: "Volunteer Work", icon: "HandHeart" },
  { id: "internship", label: "Internships", icon: "BookOpen" }
];